config/routes.rb
Rails.application.routes.draw do
  resources :app_appointments
  get 'web_app/Calender'
	
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app_appointment.rb
class AppAppointment < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/app_appointments_controller.rb
class AppAppointmentsController < ApplicationController
  before_action :set_app_appointment, only: [:show, :edit, :update, :destroy]

  # GET /app_appointments
  # GET /app_appointments.json
  def index
    @app_appointments = AppAppointment.all
  end

  # GET /app_appointments/1
  # GET /app_appointments/1.json
  def show
  end

  # GET /app_appointments/new
  def new
    @app_appointment = AppAppointment.new
  end

  # GET /app_appointments/1/edit
  def edit
  end

  # POST /app_appointments
  # POST /app_appointments.json
  def create
    @app_appointment = AppAppointment.new(app_appointment_params)

    respond_to do |format|
      if @app_appointment.save
        format.html { redirect_to @app_appointment, notice: 'App appointment was successfully created.' }
        format.json { render :show, status: :created, location: @app_appointment }
      else
        format.html { render :new }
        format.json { render json: @app_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_appointments/1
  # PATCH/PUT /app_appointments/1.json
  def update
    respond_to do |format|
      if @app_appointment.update(app_appointment_params)
        format.html { redirect_to @app_appointment, notice: 'App appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_appointment }
      else
        format.html { render :edit }
        format.json { render json: @app_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_appointments/1
  # DELETE /app_appointments/1.json
  def destroy
    @app_appointment.destroy
    respond_to do |format|
      format.html { redirect_to app_appointments_url, notice: 'App appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_appointment
      @app_appointment = AppAppointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_appointment_params
      params.require(:app_appointment).permit(:AppointmentBody, :DatenTime)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/web_app_controller.rb
class WebAppController < ApplicationController
  def Calender
  end
end

app/helpers/app_appointments_helper.rb
module AppAppointmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_app_helper.rb
module WebAppHelper
end

app/views/app_appointments/_form.html.erb
<%= form_with(model: app_appointment, local: true) do |form| %>
  <% if app_appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app_appointment.errors.count, "error") %> prohibited this app_appointment from being saved:</h2>

      <ul>
      <% app_appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :AppointmentBody %>
    <%= form.text_area :AppointmentBody %>
  </div>

  <div class="field">
    <%= form.label :DatenTime %>
    <%= form.datetime_select :DatenTime %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <div class="field">
    <%= form.label :Search %>
    <%= form.text_area :AppointmentBody %>
  </div>
    <div class="actions">
    <%= form.button :Search %>
  </div>


<% end %>

app/views/app_appointments/edit.html.erb
<h1>Editing App Appointment</h1>

<%= render 'form', app_appointment: @app_appointment %>

<%= link_to 'Show', @app_appointment %> |
<%= link_to 'Back', app_appointments_path %>

app/views/app_appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>App Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Appointmentbody</th>
      <th>Datentime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_appointments.each do |app_appointment| %>
      <tr>
        <td><%= app_appointment.AppointmentBody %></td>
        <td><%= app_appointment.DatenTime %></td>
        <td><%= link_to 'Show', app_appointment %></td>
        <td><%= link_to 'Edit', edit_app_appointment_path(app_appointment) %></td>
        <td><%= link_to 'Destroy', app_appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App Appointment', new_app_appointment_path %>

app/views/app_appointments/new.html.erb
<h1>New App Appointment</h1>

<%= render 'form', app_appointment: @app_appointment %>

<%= link_to 'Back', app_appointments_path %>

app/views/app_appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appointmentbody:</strong>
  <%= @app_appointment.AppointmentBody %>
</p>

<p>
  <strong>Datentime:</strong>
  <%= @app_appointment.DatenTime %>
</p>

<%= link_to 'Edit', edit_app_appointment_path(@app_appointment) %> |
<%= link_to 'Back', app_appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalenderWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/web_app/Calendar.html.erb
<!DOCTYPE html>
<html>
<!-- https://yuilibrary.com/yui/docs/calendar/calendar-simple.html -->
<head>
	<title>Calendar</title>
</head>

<body class="yui3-skin-sam">
	<style>
		.yui3-button {
		    margin:10px 0px 10px 0px;
		    color: #fff;
		    background-color: #3476b7;
		}
	</style>


<div id="demo" class="yui3-skin-sam yui3-g">

  <div id="leftcolumn" class="yui3-u">
     <div id="mycalendar"></div>
	<button type="button" value=1 onclick = "button(1)">Search</button>
     <button type="button" value=2 onclick = "button(2)">Create recurring</button>
     <button type="button" value=3 onclick = "button(3)">All appointments between two dates</button>
  </div>

  <div id="rightcolumn" class="yui3-u">
   <div id="links" style="padding-left:20px;">
      Selected date: <span id="selecteddate"></span>
   </div>
  </div>
</div>


<script src="http://yui.yahooapis.com/3.18.1/build/yui/yui-min.js"></script>

<script type="text/javascript">
  YUI().use('calendar', 'datatype-date', 'cssbutton',  function(Y) {

      var calendar = new Y.Calendar({
        contentBox: "#mycalendar",
        width:'500px',
        date: new Date()}).render();

      var dtdate = Y.DataType.Date;

      calendar.on("selectionChange", function (ev) {

        var newDate = ev.newSelection[0];

        Y.one("#selecteddate").setHTML(dtdate.format(newDate));//print islemi
      });

  });

function button(id) {
	    if(id == 1){
	    }
	    else if(id == 2){
	      day = prompt("Enter a day for recurring appointment");
	      appointment = prompt("Enter text for appointment");
	    }
	    else if(id == 3){
	    }
	  }
  
  </script>

	</body>
</html>

app/views/web_app/Calender.html.erb
<!DOCTYPE html>
<html>
<!-- https://yuilibrary.com/yui/docs/calendar/calendar-simple.html -->
<head>
	<title>Calendar</title>
</head>

<body class="yui3-skin-sam">
	<style>
		.yui3-button {
		    margin:10px 0px 10px 0px;
		    color: #fff;
		    background-color: #3476b7;
		}
	</style>


<div id="demo" class="yui3-skin-sam yui3-g">

  <div id="leftcolumn" class="yui3-u">
     <div id="mycalendar"></div>
	<button type="button" value=1 onclick = "button(1)">Search</button>
     <button type="button" value=2 onclick = "button(2)">Create recurring</button>
     <button type="button" value=3 onclick = "button(3)">All appointments between two dates</button>
  </div>

  <div id="rightcolumn" class="yui3-u">
   <div id="links" style="padding-left:20px;">
      Selected date: <span id="selecteddate"></span>
   </div>
  </div>
</div>


<script src="http://yui.yahooapis.com/3.18.1/build/yui/yui-min.js"></script>

<script type="text/javascript">
  YUI().use('calendar', 'datatype-date', 'cssbutton',  function(Y) {

      var calendar = new Y.Calendar({
        contentBox: "#mycalendar",
        width:'500px',
        date: new Date()}).render();

      var dtdate = Y.DataType.Date;

      calendar.on("selectionChange", function (ev) {

        var newDate = ev.newSelection[0];

        Y.one("#selecteddate").setHTML(dtdate.format(newDate));//print islemi
      });

  });

function button(id) {
	    if(id == 1){
	    }
	    else if(id == 2){
	      day = prompt("Enter a day for recurring appointment");
	      appointment = prompt("Enter text for appointment");
	    }
	    else if(id == 3){
	    }
	  }
  
  </script>

	</body>
</html>